package nu.shell.wldroid.proot

import android.app.Application
import com.google.common.truth.Truth.assertThat
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File

/**
 * Unit tests for [ProotDnsManager].
 *
 * Since ProotDnsManager requires an Android Context for ConnectivityManager,
 * and unit tests run on the JVM (with isReturnDefaultValues=true), we test:
 * - Fallback DNS behavior (ConnectivityManager returns null/default)
 * - resolv.conf file generation (given a rootfs directory)
 * - Edge cases in file handling
 *
 * With isReturnDefaultValues=true, Application() can be instantiated and
 * getSystemService() returns null, triggering ProotDnsManager's fallback path.
 */
class ProotDnsManagerTest {

    @get:Rule
    val tempDir = TemporaryFolder()

    /**
     * With returnDefaultValues=true, context.getSystemService() returns null,
     * so getSystemDnsServers() should fall back to Google DNS.
     */
    @Test
    fun `getSystemDnsServers falls back to Google DNS when context returns defaults`() {
        val manager = ProotDnsManager(Application())
        val servers = manager.getSystemDnsServers()
        assertThat(servers).containsExactly("8.8.8.8", "8.8.4.4").inOrder()
    }

    @Test
    fun `writeResolvConf creates resolv conf with nameservers`() {
        val rootfs = tempDir.newFolder("rootfs")
        val etcDir = File(rootfs, "etc")
        etcDir.mkdirs()

        val manager = ProotDnsManager(Application())
        manager.writeResolvConf(rootfs)

        val resolvConf = File(etcDir, "resolv.conf")
        assertThat(resolvConf.exists()).isTrue()

        val content = resolvConf.readText()
        assertThat(content).contains("nameserver 8.8.8.8")
        assertThat(content).contains("nameserver 8.8.4.4")
        assertThat(content).contains("Generated by WLDroid")
    }

    @Test
    fun `writeResolvConf does not crash when etc dir is missing`() {
        val rootfs = tempDir.newFolder("rootfs-no-etc")
        // No /etc directory — writeResolvConf should just return without error
        val manager = ProotDnsManager(Application())
        manager.writeResolvConf(rootfs)

        val resolvConf = File(rootfs, "etc/resolv.conf")
        assertThat(resolvConf.exists()).isFalse()
    }

    @Test
    fun `writeResolvConf replaces existing resolv conf`() {
        val rootfs = tempDir.newFolder("rootfs-existing")
        val etcDir = File(rootfs, "etc")
        etcDir.mkdirs()
        val resolvConf = File(etcDir, "resolv.conf")
        resolvConf.writeText("nameserver 127.0.0.53")

        val manager = ProotDnsManager(Application())
        manager.writeResolvConf(rootfs)

        val content = resolvConf.readText()
        assertThat(content).doesNotContain("127.0.0.53")
        assertThat(content).contains("nameserver 8.8.8.8")
    }

    @Test
    fun `writeResolvConf output format has one nameserver per line`() {
        val rootfs = tempDir.newFolder("rootfs-format")
        val etcDir = File(rootfs, "etc")
        etcDir.mkdirs()

        val manager = ProotDnsManager(Application())
        manager.writeResolvConf(rootfs)

        val lines = File(etcDir, "resolv.conf").readLines()
        val nameserverLines = lines.filter { it.startsWith("nameserver ") }
        assertThat(nameserverLines).hasSize(2)
        assertThat(nameserverLines[0]).isEqualTo("nameserver 8.8.8.8")
        assertThat(nameserverLines[1]).isEqualTo("nameserver 8.8.4.4")
    }

    @Test
    fun `writeResolvConf includes header comment`() {
        val rootfs = tempDir.newFolder("rootfs-header")
        val etcDir = File(rootfs, "etc")
        etcDir.mkdirs()

        val manager = ProotDnsManager(Application())
        manager.writeResolvConf(rootfs)

        val lines = File(etcDir, "resolv.conf").readLines()
        val commentLines = lines.filter { it.startsWith("#") }
        assertThat(commentLines).isNotEmpty()
    }

    @Test
    fun `FALLBACK_DNS contains Google DNS servers`() {
        // Verify the fallback is exercised (via reflection or by observing behavior)
        // When getSystemService returns null, we always get back exactly Google DNS
        val manager = ProotDnsManager(Application())
        val servers = manager.getSystemDnsServers()
        assertThat(servers).hasSize(2)
        assertThat(servers.first()).isEqualTo("8.8.8.8")
        assertThat(servers.last()).isEqualTo("8.8.4.4")
    }
}
