package nu.shell.wldroid.launcher

import nu.shell.wldroid.proot.ProotConfig
import nu.shell.wldroid.proot.ProotExecutor
import nu.shell.wldroid.proot.RootfsEnvironment
import java.io.File

/**
 * Manages XWayland wrapper script generation and runtime setup.
 *
 * wlroots fork+execs the binary pointed to by the `WLR_XWAYLAND` environment variable.
 * This manager generates a wrapper script that invokes proot to run the glibc
 * `/usr/bin/Xwayland` binary, preserving the FDs (`-listenfd`, `-wm`, `-displayfd`)
 * that wlroots passes to the XWayland process.
 *
 * Exec chain: wrapper.sh → proot → /usr/bin/Xwayland
 * FDs survive because proot uses ptrace, not containerization.
 */
class XWaylandManager(
    private val prootConfig: ProotConfig,
    private val cacheDir: String,
) {
    /** Path where the wrapper script will be written. */
    val wrapperScriptPath: String
        get() = "$cacheDir/xwayland-wrapper.sh"

    /**
     * Generate the wrapper script that wlroots will fork+exec.
     *
     * @param environment The rootfs environment containing Xwayland
     * @return The absolute path to the generated wrapper script
     */
    fun extractWrapperScript(environment: RootfsEnvironment): String {
        val script = buildWrapperScript(environment)
        File(wrapperScriptPath).apply {
            parentFile?.mkdirs()
            writeText(script)
            setExecutable(true)
        }
        return wrapperScriptPath
    }

    /**
     * Build the shell script content for the XWayland wrapper.
     *
     * The script:
     * 1. Sets PROOT_LOADER and PROOT_TMP_DIR if needed
     * 2. Execs proot with the rootfs, binding /dev, /proc, /tmp
     * 3. Passes all arguments ("$@") through to /usr/bin/Xwayland
     *
     * FDs from wlroots (-listenfd, -wm, -displayfd) are inherited through
     * the entire exec chain because proot uses ptrace (not containers).
     */
    internal fun buildWrapperScript(environment: RootfsEnvironment): String {
        val rootfsPath = environment.rootfsPath
        val prootBinary = prootConfig.prootBinaryPath
        val loaderExport = if (prootConfig.prootLoaderPath.isNotEmpty()) {
            "export PROOT_LOADER=\"${prootConfig.prootLoaderPath}\"\n"
        } else {
            ""
        }

        return buildString {
            appendLine("#!/system/bin/sh")
            appendLine("# XWayland wrapper — generated by WLDroid XWaylandManager")
            appendLine("# wlroots fork+execs this script; it runs Xwayland via proot")
            append(loaderExport)
            appendLine("export PROOT_TMP_DIR=\"$cacheDir/proot-tmp\"")
            appendLine("exec $prootBinary \\")
            appendLine("    -0 \\")
            appendLine("    -r \"$rootfsPath\" \\")
            appendLine("    -b /dev \\")
            appendLine("    -b /proc \\")
            appendLine("    -b /tmp \\")
            appendLine("    /usr/bin/Xwayland \"\$@\"")
        }
    }

    /**
     * Ensure the /tmp/.X11-unix directory exists on the host for X11 socket sharing.
     *
     * Both the compositor (host) and proot apps need access to the same X11 socket.
     * This directory must exist before XWayland starts.
     *
     * @param tempDir The host path that maps to proot's /tmp
     */
    fun ensureTmpDirReady(tempDir: String) {
        File(tempDir, ".X11-unix").mkdirs()
    }

    /**
     * Check if the Xwayland binary is installed in the rootfs.
     *
     * @return true if `/usr/bin/Xwayland` is available inside the rootfs
     */
    suspend fun isXWaylandInstalled(
        packageInstaller: PackageInstaller,
        environment: RootfsEnvironment,
    ): Boolean = packageInstaller.isCommandAvailable(environment, "Xwayland")
}
