package nu.shel.wldroid.proot

import android.content.Context
import android.net.ConnectivityManager
import android.util.Log
import java.io.File
import java.net.Inet6Address
import java.net.InetAddress

/**
 * Manages DNS configuration for proot environments by querying Android's
 * ConnectivityManager for the device's actual DNS servers.
 *
 * Proot doesn't run systemd, so systemd-resolved (127.0.0.53) won't work.
 * Instead, we query Android's active network for DNS servers and write them
 * to the rootfs /etc/resolv.conf before each proot invocation. This ensures
 * VPN DNS, corporate DNS, and other custom configurations are respected.
 */
class ProotDnsManager(private val context: Context) {

    companion object {
        private const val TAG = "ProotDnsManager"
        private val FALLBACK_DNS = listOf("8.8.8.8", "8.8.4.4")
    }

    /**
     * Gets DNS servers from Android's active network.
     * Returns the device's configured DNS servers, preferring IPv4.
     * Falls back to Google DNS if no servers are available.
     */
    fun getSystemDnsServers(): List<String> {
        return try {
            val cm = context.getSystemService(Context.CONNECTIVITY_SERVICE) as? ConnectivityManager
                ?: return FALLBACK_DNS

            val activeNetwork = cm.activeNetwork ?: return FALLBACK_DNS
            val linkProperties = cm.getLinkProperties(activeNetwork) ?: return FALLBACK_DNS
            val dnsServers = linkProperties.dnsServers

            if (dnsServers.isEmpty()) return FALLBACK_DNS

            // Sort: IPv4 first (more compatible in proot), then IPv6
            val sorted = dnsServers.sortedBy { it is Inet6Address }
            val result = sorted.map { formatDnsAddress(it) }

            Log.d(TAG, "System DNS servers: $result")
            result
        } catch (e: Exception) {
            Log.w(TAG, "Failed to query system DNS, using fallback", e)
            FALLBACK_DNS
        }
    }

    /**
     * Writes /etc/resolv.conf in the given rootfs environment with the
     * device's current DNS servers. Handles symlinks (e.g. Trixie's
     * systemd-resolved stub symlink).
     */
    fun writeResolvConf(rootfsDir: File) {
        val etcDir = File(rootfsDir, "etc")
        if (!etcDir.exists()) {
            Log.w(TAG, "etc dir doesn't exist in rootfs: ${etcDir.absolutePath}")
            return
        }

        val resolvConf = File(etcDir, "resolv.conf")

        // Delete first to handle symlinks (Trixie symlinks to systemd-resolved stub)
        resolvConf.delete()

        val dnsServers = getSystemDnsServers()
        val content = buildString {
            appendLine("# Generated by WLDroid — do not edit")
            appendLine("# DNS servers from Android active network")
            for (server in dnsServers) {
                appendLine("nameserver $server")
            }
        }

        resolvConf.writeText(content)
        Log.d(TAG, "Wrote resolv.conf with ${dnsServers.size} nameservers: $dnsServers")
    }

    private fun formatDnsAddress(addr: InetAddress): String {
        val hostAddress = addr.hostAddress ?: return addr.toString()
        // IPv6 addresses from getHostAddress() may have scope IDs (e.g. "fe80::1%wlan0")
        // resolv.conf doesn't support scope IDs, strip them
        return if (addr is Inet6Address && hostAddress.contains('%')) {
            hostAddress.substringBefore('%')
        } else {
            hostAddress
        }
    }
}
